"""Business manager for chat AI assist features."""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Sequence

from client.core.datetime_utils import to_epoch_seconds
from client.managers.ai_prompt_builder import (
    AIAssistAction,
    AIPromptBuilder,
    ReplySuggestionParseDiagnostics,
    ReplySummaryContext,
    coerce_assist_action,
    latest_peer_text_message,
    latest_peer_text_message_group,
)
from client.managers.ai_task_manager import AITaskManager, AITaskSnapshot, AITaskState, get_ai_task_manager
from client.managers.conversation_memory_manager import ConversationMemoryManager
from client.models.message import ChatMessage, MessageType, Session
from client.core import logging
from client.core.secure_storage import SecureStorage
from client.services.ai_service import AIErrorCode
from client.storage.database import Database, get_database


logger = logging.get_logger(__name__)


class AIReplySuggestionStatus(Enum):
    """In-memory lifecycle for reply candidates."""

    IDLE = "idle"
    RUNNING = "running"
    READY = "ready"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass(slots=True)
class AIReplySuggestionItem:
    """One candidate reply generated by AI."""

    text: str
    rank: int
    anchor_message_id: str
    task_id: str


@dataclass(slots=True)
class AIReplySuggestionState:
    """Current in-memory reply suggestion state for one session."""

    session_id: str
    anchor_message_id: str = ""
    status: AIReplySuggestionStatus = AIReplySuggestionStatus.IDLE
    items: list[AIReplySuggestionItem] = field(default_factory=list)
    task_id: str = ""
    error_code: Optional[AIErrorCode] = None
    reason: str = ""
    updated_at: float = field(default_factory=time.time)

    def copy(self) -> "AIReplySuggestionState":
        """Return a detached copy for callers."""
        return AIReplySuggestionState(
            session_id=self.session_id,
            anchor_message_id=self.anchor_message_id,
            status=self.status,
            items=[
                AIReplySuggestionItem(
                    text=item.text,
                    rank=item.rank,
                    anchor_message_id=item.anchor_message_id,
                    task_id=item.task_id,
                )
                for item in self.items
            ],
            task_id=self.task_id,
            error_code=self.error_code,
            reason=self.reason,
            updated_at=self.updated_at,
        )


@dataclass(frozen=True, slots=True)
class AIAssistResult:
    """Result of one draft-assist request."""

    task_id: str
    action: AIAssistAction
    text: str = ""
    state: AITaskState = AITaskState.DONE
    error_code: Optional[AIErrorCode] = None
    error_message: str = ""
    truncated: bool = False
    finish_reason: str = ""


@dataclass(frozen=True, slots=True)
class AIFileSummaryResult:
    """Result of one local file-summary request."""

    task_id: str
    text: str = ""
    state: AITaskState = AITaskState.DONE
    error_code: Optional[AIErrorCode] = None
    error_message: str = ""
    truncated: bool = False
    finish_reason: str = ""


class AIAssistManager:
    """Coordinate prompt building, AI task execution, and ephemeral candidates."""

    # Reply suggestions already include direct recent messages, so skip very recent closed summaries here only.
    REPLY_SUMMARY_MIN_AGE_SECONDS = 300
    REPLY_WEEKLY_HISTORY_MAX_AGE_SECONDS = 7 * 24 * 60 * 60
    REPLY_WEEKLY_HISTORY_BUCKET_LIMIT = 6
    REPLY_WEEKLY_HISTORY_MAX_CHARS = 240
    REPLY_HISTORY_RECALL_LIMIT = 3
    REPLY_HISTORY_MAX_AGE_SECONDS = 7 * 24 * 60 * 60
    REPLY_HISTORY_RECALL_MAX_CHARS = 700

    def __init__(
        self,
        task_manager: AITaskManager | None = None,
        prompt_builder: AIPromptBuilder | None = None,
        db: Database | None = None,
        memory_manager: ConversationMemoryManager | None = None,
    ) -> None:
        self._task_manager = task_manager or get_ai_task_manager()
        self._prompt_builder = prompt_builder or AIPromptBuilder()
        self._db = db or get_database()
        self._memory_manager = memory_manager
        self._reply_suggestions: dict[str, AIReplySuggestionState] = {}

    async def assist_draft(
        self,
        action: AIAssistAction | str,
        text: str,
        *,
        session: Session | None = None,
        target_language: str = "中文",
    ) -> AIAssistResult:
        """Run one draft editing task and return the generated text."""
        normalized_action = coerce_assist_action(action)
        request = self._prompt_builder.build_draft_request(
            normalized_action,
            text,
            session=session,
            task_id=self._task_id(normalized_action.value),
            target_language=target_language,
        )
        snapshot = await self._task_manager.run_once(request)
        return self._assist_result(normalized_action, snapshot)

    async def translate_message(
        self,
        text: str,
        *,
        session: Session | None = None,
        message_id: str = "",
        target_language_code: str = "zh-CN",
        mode: str = "manual",
    ) -> AIAssistResult:
        """Translate one persisted chat message using the local AI provider."""
        normalized_mode = str(mode or "manual").strip().lower() or "manual"
        request = self._prompt_builder.build_message_translation_request(
            text,
            session=session,
            message_id=message_id,
            target_language_code=target_language_code,
            mode=normalized_mode,
            task_id=self._task_id(AIAssistAction.TRANSLATE.value),
        )
        logger.info(
            "[ai-perf] translation_request task_id=%s session_id=%s message_id=%s mode=%s target_language=%s "
            "source_chars=%s prompt_chars=%s",
            request.task_id,
            request.session_id,
            str(message_id or ""),
            normalized_mode,
            str(target_language_code or "").strip(),
            request.metadata.get("source_chars"),
            request.metadata.get("prompt_chars"),
        )
        snapshot = await self._task_manager.run_once(request)
        return self._translation_result(snapshot, mode=normalized_mode)

    async def summarize_file_text(
        self,
        session: Session | None,
        file_name: str,
        text: str,
        *,
        message_id: str = "",
    ) -> AIFileSummaryResult:
        """Summarize extracted local file text without sending it to the server."""
        request = self._prompt_builder.build_file_summary_request(
            file_name,
            text,
            session=session,
            message_id=message_id,
            task_id=self._task_id("file-summary"),
        )
        logger.info(
            "[ai-perf] file_summary_request task_id=%s session_id=%s message_id=%s file_name=%s source_chars=%s prompt_chars=%s",
            request.task_id,
            request.session_id,
            str(message_id or ""),
            str(request.metadata.get("file_name") or ""),
            request.metadata.get("source_chars"),
            request.metadata.get("prompt_chars"),
        )
        snapshot = await self._task_manager.run_once(request)
        text_output = snapshot.content.strip() if snapshot.state == AITaskState.DONE else ""
        return AIFileSummaryResult(
            task_id=snapshot.task_id,
            text=text_output,
            state=snapshot.state,
            error_code=snapshot.error_code,
            error_message=snapshot.error_message,
            truncated=snapshot.truncated,
            finish_reason=snapshot.finish_reason,
        )

    def can_suggest_replies(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str = "",
    ) -> tuple[bool, str]:
        """Return whether reply suggestions should be requested for the current context."""
        eligible, reason, _anchor = self._reply_suggestion_eligibility(
            session,
            messages,
            current_user_id=current_user_id,
            include_duplicate=True,
        )
        return eligible, reason

    async def suggest_replies(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str = "",
    ) -> AIReplySuggestionState:
        """Generate private reply suggestions and keep them only in memory."""
        eligible, reason, anchor = self._reply_suggestion_eligibility(
            session,
            messages,
            current_user_id=current_user_id,
            include_duplicate=False,
        )
        if not eligible:
            existing = self._reply_suggestions.get(session.session_id)
            if reason == "duplicate_anchor" and existing is not None:
                return existing.copy()
            return AIReplySuggestionState(
                session_id=session.session_id,
                anchor_message_id=getattr(anchor, "message_id", ""),
                status=AIReplySuggestionStatus.IDLE,
                reason=reason,
            )

        summary_context = await self._load_reply_summary_context(
            session.session_id,
            messages,
            current_user_id=current_user_id,
        )
        initial_built = self._prompt_builder.build_reply_suggestion_request(
            session,
            messages,
            task_id=self._task_id(AIAssistAction.REPLY_SUGGESTION.value),
            current_user_id=current_user_id,
            summary_context=summary_context,
        )
        logger.info(
            "[ai-perf] reply_suggestion_request task_id=%s session_id=%s anchor_message_id=%s "
            "anchor_group_size=%s recent_context_count=%s has_summary=%s has_weekly_summary=%s "
            "history_recall_count=%s has_rag_history_context=%s rag_history_count=%s prompt_chars=%s",
            initial_built.request.task_id,
            initial_built.request.session_id,
            initial_built.request.metadata.get("anchor_message_id"),
            initial_built.request.metadata.get("anchor_group_size"),
            initial_built.request.metadata.get("recent_context_count"),
            initial_built.request.metadata.get("has_summary"),
            initial_built.request.metadata.get("has_weekly_history_summary"),
            initial_built.request.metadata.get("history_recall_count"),
            initial_built.request.metadata.get("has_rag_history_context"),
            initial_built.request.metadata.get("rag_history_count"),
            initial_built.request.metadata.get("prompt_chars"),
        )
        running = AIReplySuggestionState(
            session_id=session.session_id,
            anchor_message_id=initial_built.anchor_message.message_id,
            status=AIReplySuggestionStatus.RUNNING,
            task_id=initial_built.request.task_id,
        )
        self._reply_suggestions[session.session_id] = running

        state = await self._generate_reply_suggestions_once(
            session,
            messages,
            current_user_id=current_user_id,
            summary_context=summary_context,
        )
        self._reply_suggestions[session.session_id] = state
        return state.copy()

    def get_suggestions(self, session_id: str) -> AIReplySuggestionState | None:
        """Return current in-memory reply suggestions for a session."""
        state = self._reply_suggestions.get(str(session_id or "").strip())
        return state.copy() if state is not None else None

    def clear_suggestions(self, session_id: str) -> None:
        """Clear reply candidates for a session."""
        self._reply_suggestions.pop(str(session_id or "").strip(), None)

    def has_running_non_summary_task(self) -> bool:
        """Return whether a non-summary AI task is currently running."""
        return self._task_manager.has_running_non_summary_task()

    def invalidate_for_sent_message(self, session_id: str) -> None:
        """Discard reply candidates once the user sends a message."""
        self.clear_suggestions(session_id)

    def invalidate_for_new_message(self, session_id: str, message: ChatMessage) -> None:
        """Discard candidates when the conversation receives a newer message."""
        normalized_session_id = str(session_id or "").strip()
        state = self._reply_suggestions.get(normalized_session_id)
        if state is None:
            return
        if message.session_id != normalized_session_id:
            return
        if message.message_id != state.anchor_message_id:
            self.clear_suggestions(normalized_session_id)

    async def close(self) -> None:
        """Clear in-memory state and release the singleton reference."""
        self._reply_suggestions.clear()
        global _ai_assist_manager
        if _ai_assist_manager is self:
            _ai_assist_manager = None

    def _reply_suggestion_eligibility(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str,
        include_duplicate: bool,
    ) -> tuple[bool, str, ChatMessage | None]:
        if session.is_ai_session or session.session_type == "ai":
            return False, "ai_session", None
        if session.session_type not in {"direct", "private"}:
            return False, "unsupported_session_type", None
        normalized_current_user_id = str(current_user_id or "").strip()
        latest_visible_text = next(
            (
                message
                for message in reversed(list(messages or []))
                if message.message_type == MessageType.TEXT
                and not message.is_ai
                and str(getattr(message.status, "value", message.status)) not in {"failed", "recalled"}
                and str(message.content or "").strip()
            ),
            None,
        )
        if latest_visible_text is not None:
            latest_is_self = bool(latest_visible_text.is_self)
            if normalized_current_user_id and str(latest_visible_text.sender_id or "").strip() == normalized_current_user_id:
                latest_is_self = True
            if latest_is_self:
                return False, "latest_text_from_self", None

        anchor = latest_peer_text_message(messages, current_user_id=current_user_id)
        if anchor is None:
            return False, "no_peer_text_message", None

        state = self._reply_suggestions.get(session.session_id)
        if state is not None and state.anchor_message_id == anchor.message_id:
            if state.status in {AIReplySuggestionStatus.RUNNING, AIReplySuggestionStatus.READY}:
                if not include_duplicate:
                    return False, "duplicate_anchor", anchor
        return True, "", anchor

    def _state_from_snapshot(
        self,
        session_id: str,
        anchor_message: ChatMessage,
        snapshot: AITaskSnapshot,
        *,
        recent_messages: Sequence[ChatMessage],
    ) -> tuple[AIReplySuggestionState, ReplySuggestionParseDiagnostics | None]:
        anchor_message_id = anchor_message.message_id
        if snapshot.state == AITaskState.CANCELLED:
            return AIReplySuggestionState(
                session_id=session_id,
                anchor_message_id=anchor_message_id,
                status=AIReplySuggestionStatus.CANCELLED,
                task_id=snapshot.task_id,
                error_code=AIErrorCode.AI_USER_CANCELLED,
                reason=snapshot.finish_reason,
            ), None
        if snapshot.state != AITaskState.DONE:
            return AIReplySuggestionState(
                session_id=session_id,
                anchor_message_id=anchor_message_id,
                status=AIReplySuggestionStatus.FAILED,
                task_id=snapshot.task_id,
                error_code=snapshot.error_code or AIErrorCode.AI_MODEL_UNAVAILABLE,
                reason=snapshot.error_message or snapshot.finish_reason,
            ), None

        parsed, diagnostics = self._prompt_builder.parse_reply_suggestions_with_diagnostics(
            snapshot.content,
            limit=self._prompt_builder.REPLY_SUGGESTION_COUNT,
            anchor_message=anchor_message,
            recent_messages=recent_messages,
        )
        if not parsed:
            state = AIReplySuggestionState(
                session_id=session_id,
                anchor_message_id=anchor_message_id,
                status=AIReplySuggestionStatus.FAILED,
                task_id=snapshot.task_id,
                error_code=AIErrorCode.AI_OUTPUT_INVALID,
                reason=AIErrorCode.AI_OUTPUT_INVALID.value,
            )
            return state, diagnostics

        return AIReplySuggestionState(
            session_id=session_id,
            anchor_message_id=anchor_message_id,
            status=AIReplySuggestionStatus.READY,
            items=[
                AIReplySuggestionItem(
                    text=text,
                    rank=index + 1,
                    anchor_message_id=anchor_message_id,
                    task_id=snapshot.task_id,
                )
                for index, text in enumerate(parsed)
            ],
            task_id=snapshot.task_id,
            reason=snapshot.finish_reason,
        ), diagnostics

    async def _generate_reply_suggestions_once(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str,
        summary_context: ReplySummaryContext,
    ) -> AIReplySuggestionState:
        anchor_message = latest_peer_text_message(messages, current_user_id=current_user_id)
        if anchor_message is None:
            return AIReplySuggestionState(
                session_id=session.session_id,
                status=AIReplySuggestionStatus.FAILED,
                error_code=AIErrorCode.AI_OUTPUT_INVALID,
                reason=AIErrorCode.AI_OUTPUT_INVALID.value,
            )
        standard_built = self._prompt_builder.build_reply_suggestion_request(
            session,
            messages,
            task_id=self._task_id(AIAssistAction.REPLY_SUGGESTION.value),
            current_user_id=current_user_id,
            summary_context=summary_context,
        )
        snapshot = await self._task_manager.run_once(standard_built.request)
        state, diagnostics = self._state_from_snapshot(
            session.session_id,
            standard_built.anchor_message,
            snapshot,
            recent_messages=messages,
        )
        if state.status == AIReplySuggestionStatus.CANCELLED:
            return state
        if not (
            state.status == AIReplySuggestionStatus.FAILED
            and state.error_code == AIErrorCode.AI_OUTPUT_INVALID
            and snapshot.state == AITaskState.DONE
        ):
            return state

        self._log_reply_suggestion_parse_failure(
            task_id=snapshot.task_id,
            session_id=session.session_id,
            anchor_message_id=standard_built.anchor_message.message_id,
            output=snapshot.content,
            diagnostics=diagnostics,
            prompt_mode=str(standard_built.request.metadata.get("reply_prompt_mode") or "standard"),
        )

        fallback_built = self._prompt_builder.build_reply_suggestion_request(
            session,
            messages,
            task_id=self._task_id(AIAssistAction.REPLY_SUGGESTION.value),
            current_user_id=current_user_id,
            max_context_messages=min(4, self._prompt_builder.MAX_CONTEXT_MESSAGES),
            summary_context=ReplySummaryContext(),
            fallback_mode=True,
        )
        logger.info(
            "[ai-perf] reply_suggestion_retry_request task_id=%s session_id=%s anchor_message_id=%s "
            "anchor_group_size=%s recent_context_count=%s has_summary=%s has_weekly_summary=%s "
            "history_recall_count=%s has_rag_history_context=%s rag_history_count=%s prompt_chars=%s",
            fallback_built.request.task_id,
            fallback_built.request.session_id,
            fallback_built.request.metadata.get("anchor_message_id"),
            fallback_built.request.metadata.get("anchor_group_size"),
            fallback_built.request.metadata.get("recent_context_count"),
            fallback_built.request.metadata.get("has_summary"),
            fallback_built.request.metadata.get("has_weekly_history_summary"),
            fallback_built.request.metadata.get("history_recall_count"),
            fallback_built.request.metadata.get("has_rag_history_context"),
            fallback_built.request.metadata.get("rag_history_count"),
            fallback_built.request.metadata.get("prompt_chars"),
        )
        fallback_snapshot = await self._task_manager.run_once(fallback_built.request)
        fallback_state, fallback_diagnostics = self._state_from_snapshot(
            session.session_id,
            fallback_built.anchor_message,
            fallback_snapshot,
            recent_messages=messages,
        )
        if (
            fallback_state.status == AIReplySuggestionStatus.FAILED
            and fallback_state.error_code == AIErrorCode.AI_OUTPUT_INVALID
            and fallback_snapshot.state == AITaskState.DONE
        ):
            self._log_reply_suggestion_parse_failure(
                task_id=fallback_snapshot.task_id,
                session_id=session.session_id,
                anchor_message_id=fallback_built.anchor_message.message_id,
                output=fallback_snapshot.content,
                diagnostics=fallback_diagnostics,
                prompt_mode=str(fallback_built.request.metadata.get("reply_prompt_mode") or "fallback"),
            )
        return fallback_state

    @staticmethod
    def _log_reply_suggestion_parse_failure(
        *,
        task_id: str,
        session_id: str,
        anchor_message_id: str,
        output: str,
        diagnostics: ReplySuggestionParseDiagnostics | None,
        prompt_mode: str,
    ) -> None:
        parsed = diagnostics or ReplySuggestionParseDiagnostics(output_preview="")
        logger.info(
            "[ai-perf] reply_suggestion_parse_invalid task_id=%s session_id=%s anchor_message_id=%s "
            "prompt_mode=%s output_chars=%s raw_segments=%s cleaned_candidates=%s empty=%s duplicates=%s "
            "anchor_repeats=%s stale_topics=%s trimmed=%s output_preview=%s",
            task_id,
            session_id,
            anchor_message_id,
            prompt_mode,
            len(str(output or "")),
            parsed.raw_segment_count,
            parsed.cleaned_candidate_count,
            parsed.empty_count,
            parsed.duplicate_count,
            parsed.anchor_repeat_count,
            parsed.stale_topic_count,
            parsed.trimmed_count,
            parsed.output_preview,
        )

    async def _load_reply_summary_context(
        self,
        session_id: str,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str = "",
    ) -> ReplySummaryContext:
        """Load and decrypt recent local bucket summaries for one session."""
        normalized_session_id = str(session_id or "").strip()
        if not normalized_session_id or not self._db.is_connected:
            return ReplySummaryContext()

        summary_limit = max(1, int(self._prompt_builder.REPLY_HISTORY_SUMMARY_LIMIT or 1))
        open_bucket_summary = ""
        if hasattr(self._db, "get_open_conversation_summary_bucket"):
            open_bucket = await self._db.get_open_conversation_summary_bucket(normalized_session_id)
            open_bucket_summary = self._decrypt_bucket_summary(open_bucket)

        closed_buckets = await self._db.list_recent_conversation_summary_buckets(
            normalized_session_id,
            limit=max(self.REPLY_WEEKLY_HISTORY_BUCKET_LIMIT * 2, summary_limit * 3, summary_limit + 2),
            is_open=False,
            ready_only=True,
        )
        now_ts = int(time.time())
        min_allowed_end_ts = now_ts - self.REPLY_SUMMARY_MIN_AGE_SECONDS
        history_summaries: list[str] = []
        for bucket in closed_buckets:
            bucket_end_ts = int(bucket.get("bucket_end_ts") or bucket.get("last_message_ts") or bucket.get("bucket_start_ts") or 0)
            if bucket_end_ts <= 0 or bucket_end_ts > min_allowed_end_ts:
                continue
            if now_ts - bucket_end_ts > self.REPLY_WEEKLY_HISTORY_MAX_AGE_SECONDS:
                continue
            summary_text = self._decrypt_bucket_summary(bucket)
            if not summary_text:
                continue
            history_summaries.append(summary_text)
            if len(history_summaries) >= self.REPLY_WEEKLY_HISTORY_BUCKET_LIMIT:
                break

        weekly_history_summary = self._compose_weekly_history_summary(history_summaries)

        related_history_lines = await self._load_related_summary_rag_lines(
            normalized_session_id,
            messages,
            current_user_id=current_user_id,
        )

        return ReplySummaryContext(
            open_bucket_summary=open_bucket_summary,
            weekly_history_summary=weekly_history_summary,
            recent_bucket_summaries=tuple(history_summaries[:summary_limit]),
            related_history_lines=tuple(related_history_lines),
        )

    def _compose_weekly_history_summary(self, summaries: Sequence[str]) -> str:
        """Merge recent closed-bucket summaries into one bounded weekly summary."""
        unique_items: list[str] = []
        seen: set[str] = set()
        for item in summaries:
            normalized = _normalize_history_text(item)
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            unique_items.append(str(item).strip())
        if not unique_items:
            return ""

        merged = "；".join(unique_items)
        max_chars = max(1, int(self.REPLY_WEEKLY_HISTORY_MAX_CHARS or 1))
        if len(merged) <= max_chars:
            return merged

        trimmed_parts: list[str] = []
        total_chars = 0
        for item in unique_items:
            extra_chars = len(item) + (1 if trimmed_parts else 0)
            if total_chars + extra_chars > max_chars:
                break
            trimmed_parts.append(item)
            total_chars += extra_chars
        if trimmed_parts:
            return "；".join(trimmed_parts)
        return merged[:max_chars].rstrip("；，, ")

    async def _load_related_summary_rag_lines(
        self,
        session_id: str,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str = "",
    ) -> list[str]:
        """Return a few older summary lines related to the latest reply topic."""
        normalized_session_id = str(session_id or "").strip()
        if not normalized_session_id or not messages:
            return []

        context_limit = max(1, int(self._prompt_builder.MAX_CONTEXT_MESSAGES or 1))
        direct_context_messages = list(messages[-context_limit:])
        if not direct_context_messages:
            return []

        anchor_group = latest_peer_text_message_group(messages, current_user_id=current_user_id)
        if not anchor_group:
            return []

        query_text = self._reply_rag_query_text(anchor_group, direct_context_messages)
        if not query_text:
            return []

        list_ann_candidates = getattr(self._db, "list_conversation_memory_ann_candidates", None)
        if self._memory_manager is None and not callable(list_ann_candidates):
            return []

        if self._memory_manager is None:
            self._memory_manager = ConversationMemoryManager(db=self._db)
        memory_manager = self._memory_manager
        max_end_ts = self._reply_rag_max_end_ts(anchor_group, direct_context_messages)
        min_start_ts = self._reply_rag_min_start_ts(anchor_group)
        try:
            context = await memory_manager.build_reply_suggestion_rag_context(
                normalized_session_id,
                query_text,
                max_end_ts=max_end_ts,
                min_start_ts=min_start_ts,
                result_limit=self.REPLY_HISTORY_RECALL_LIMIT,
            )
        except Exception:
            logger.exception("Failed to load reply-suggestion RAG context session_id=%s", normalized_session_id)
            return []
        return self._clip_related_summary_lines(context.lines)

    def _reply_rag_query_text(
        self,
        anchor_group: Sequence[ChatMessage],
        direct_context_messages: Sequence[ChatMessage],
    ) -> str:
        """Build a bounded semantic query from current visible context only."""
        lines: list[str] = []
        seen: set[str] = set()
        for message in list(direct_context_messages or []):
            content = _normalize_history_text(str(message.content or ""))
            if not content or content in seen:
                continue
            seen.add(content)
            role = "我" if bool(message.is_self) else "对方"
            lines.append(f"{role}: {str(message.content or '').strip()}")
        anchor_text = " ".join(
            str(message.content or "").strip()
            for message in list(anchor_group or [])
            if str(message.content or "").strip()
        ).strip()
        if anchor_text:
            lines.append(f"当前待回复: {anchor_text}")
        query = " ".join(" ".join(lines).split())
        return _clip_text(query, max(1, self._prompt_builder.MAX_MESSAGE_CHARS))

    def _reply_rag_max_end_ts(
        self,
        anchor_group: Sequence[ChatMessage],
        direct_context_messages: Sequence[ChatMessage],
    ) -> int | None:
        """Return the latest summary end timestamp allowed for related-history recall."""
        timestamps = [
            int(value)
            for value in (
                to_epoch_seconds(getattr(message, "timestamp", None))
                for message in [*list(anchor_group or []), *list(direct_context_messages or [])]
            )
            if value is not None and int(value) > 0
        ]
        if not timestamps:
            return None
        latest_anchor_ts = max(timestamps)
        oldest_context_ts = min(timestamps)
        max_end_ts = min(latest_anchor_ts - self.REPLY_SUMMARY_MIN_AGE_SECONDS, oldest_context_ts - 1)
        return max_end_ts if max_end_ts > 0 else None

    def _reply_rag_min_start_ts(self, anchor_group: Sequence[ChatMessage]) -> int | None:
        """Bound reply recall to the recent-history window when timestamps are available."""
        anchor_timestamps = [
            int(value)
            for value in (to_epoch_seconds(getattr(message, "timestamp", None)) for message in list(anchor_group or []))
            if value is not None and int(value) > 0
        ]
        if not anchor_timestamps:
            return None
        return max(1, max(anchor_timestamps) - self.REPLY_HISTORY_MAX_AGE_SECONDS)

    def _clip_related_summary_lines(self, lines: Sequence[str]) -> list[str]:
        """Deduplicate and bound related summary lines before prompt insertion."""
        max_total = max(1, int(self.REPLY_HISTORY_RECALL_MAX_CHARS or 1))
        max_line = max(1, int(self._prompt_builder.MAX_MESSAGE_CHARS or 1))
        clipped: list[str] = []
        seen: set[str] = set()
        total = 0
        for line in list(lines or []):
            text = _clip_text(" ".join(str(line or "").split()), max_line)
            if not text:
                continue
            key = _normalize_history_text(text)
            if key in seen:
                continue
            extra = len(text) + (1 if clipped else 0)
            if total + extra > max_total and clipped:
                break
            seen.add(key)
            clipped.append(text)
            total += extra
            if len(clipped) >= max(1, int(self.REPLY_HISTORY_RECALL_LIMIT or 1)):
                break
        return clipped

    def _decrypt_bucket_summary(self, bucket: dict | None) -> str:
        """Return one decrypted bucket summary or an empty string when unavailable."""
        if not isinstance(bucket, dict):
            return ""
        if str(bucket.get("summary_status") or "").strip() != "ready":
            return ""
        ciphertext = str(bucket.get("display_summary_ciphertext") or "").strip()
        if not ciphertext:
            return ""
        try:
            return str(SecureStorage.decrypt_text(ciphertext) or "").strip()
        except Exception:
            logger.warning(
                "Failed to decrypt local conversation summary session_id=%s bucket_start_ts=%s",
                str(bucket.get("session_id") or ""),
                str(bucket.get("bucket_start_ts") or ""),
                exc_info=True,
            )
            return ""

    @staticmethod
    def _assist_result(action: AIAssistAction, snapshot: AITaskSnapshot) -> AIAssistResult:
        text = snapshot.content if snapshot.state == AITaskState.DONE else ""
        return AIAssistResult(
            task_id=snapshot.task_id,
            action=action,
            text=text,
            state=snapshot.state,
            error_code=snapshot.error_code,
            error_message=snapshot.error_message,
            truncated=snapshot.truncated,
            finish_reason=snapshot.finish_reason,
        )

    def _translation_result(self, snapshot: AITaskSnapshot, *, mode: str) -> AIAssistResult:
        text = ""
        if snapshot.state == AITaskState.DONE:
            text = self._prompt_builder.parse_message_translation(snapshot.content, mode=mode)
        return AIAssistResult(
            task_id=snapshot.task_id,
            action=AIAssistAction.TRANSLATE,
            text=text,
            state=snapshot.state,
            error_code=snapshot.error_code,
            error_message=snapshot.error_message,
            truncated=snapshot.truncated,
            finish_reason=snapshot.finish_reason,
        )

    @staticmethod
    def _task_id(prefix: str) -> str:
        return f"{prefix}-{uuid.uuid4()}"


_ai_assist_manager: Optional[AIAssistManager] = None


def peek_ai_assist_manager() -> Optional[AIAssistManager]:
    """Return the existing AI assist manager singleton when present."""
    return _ai_assist_manager


def get_ai_assist_manager() -> AIAssistManager:
    """Return the global AI assist manager singleton."""
    global _ai_assist_manager
    if _ai_assist_manager is None:
        _ai_assist_manager = AIAssistManager()
    return _ai_assist_manager


def _normalize_history_text(value: str) -> str:
    """Normalize one text fragment for lightweight duplicate detection."""
    text = "".join(str(value or "").strip().split()).casefold()
    return text


def _clip_text(value: str, max_chars: int) -> str:
    text = " ".join(str(value or "").split())
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip()
