"""Business manager for chat AI assist features."""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Sequence

from client.managers.ai_prompt_builder import (
    AIAssistAction,
    AIPromptBuilder,
    coerce_assist_action,
    latest_peer_text_message,
)
from client.managers.ai_task_manager import AITaskManager, AITaskSnapshot, AITaskState, get_ai_task_manager
from client.models.message import ChatMessage, MessageType, Session
from client.services.ai_service import AIErrorCode


class AIReplySuggestionStatus(Enum):
    """In-memory lifecycle for reply candidates."""

    IDLE = "idle"
    RUNNING = "running"
    READY = "ready"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass(slots=True)
class AIReplySuggestionItem:
    """One candidate reply generated by AI."""

    text: str
    rank: int
    anchor_message_id: str
    task_id: str


@dataclass(slots=True)
class AIReplySuggestionState:
    """Current in-memory reply suggestion state for one session."""

    session_id: str
    anchor_message_id: str = ""
    status: AIReplySuggestionStatus = AIReplySuggestionStatus.IDLE
    items: list[AIReplySuggestionItem] = field(default_factory=list)
    task_id: str = ""
    error_code: Optional[AIErrorCode] = None
    reason: str = ""
    updated_at: float = field(default_factory=time.time)

    def copy(self) -> "AIReplySuggestionState":
        """Return a detached copy for callers."""
        return AIReplySuggestionState(
            session_id=self.session_id,
            anchor_message_id=self.anchor_message_id,
            status=self.status,
            items=[
                AIReplySuggestionItem(
                    text=item.text,
                    rank=item.rank,
                    anchor_message_id=item.anchor_message_id,
                    task_id=item.task_id,
                )
                for item in self.items
            ],
            task_id=self.task_id,
            error_code=self.error_code,
            reason=self.reason,
            updated_at=self.updated_at,
        )


@dataclass(frozen=True, slots=True)
class AIAssistResult:
    """Result of one draft-assist request."""

    task_id: str
    action: AIAssistAction
    text: str = ""
    state: AITaskState = AITaskState.DONE
    error_code: Optional[AIErrorCode] = None
    error_message: str = ""
    truncated: bool = False
    finish_reason: str = ""


class AIAssistManager:
    """Coordinate prompt building, AI task execution, and ephemeral candidates."""

    def __init__(
        self,
        task_manager: AITaskManager | None = None,
        prompt_builder: AIPromptBuilder | None = None,
    ) -> None:
        self._task_manager = task_manager or get_ai_task_manager()
        self._prompt_builder = prompt_builder or AIPromptBuilder()
        self._reply_suggestions: dict[str, AIReplySuggestionState] = {}

    async def assist_draft(
        self,
        action: AIAssistAction | str,
        text: str,
        *,
        session: Session | None = None,
        target_language: str = "中文",
    ) -> AIAssistResult:
        """Run one draft editing task and return the generated text."""
        normalized_action = coerce_assist_action(action)
        request = self._prompt_builder.build_draft_request(
            normalized_action,
            text,
            session=session,
            task_id=self._task_id(normalized_action.value),
            target_language=target_language,
        )
        snapshot = await self._task_manager.run_once(request)
        return self._assist_result(normalized_action, snapshot)

    def can_suggest_replies(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str = "",
    ) -> tuple[bool, str]:
        """Return whether reply suggestions should be requested for the current context."""
        eligible, reason, _anchor = self._reply_suggestion_eligibility(
            session,
            messages,
            current_user_id=current_user_id,
            include_duplicate=True,
        )
        return eligible, reason

    async def suggest_replies(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str = "",
    ) -> AIReplySuggestionState:
        """Generate private reply suggestions and keep them only in memory."""
        eligible, reason, anchor = self._reply_suggestion_eligibility(
            session,
            messages,
            current_user_id=current_user_id,
            include_duplicate=False,
        )
        if not eligible:
            existing = self._reply_suggestions.get(session.session_id)
            if reason == "duplicate_anchor" and existing is not None:
                return existing.copy()
            return AIReplySuggestionState(
                session_id=session.session_id,
                anchor_message_id=getattr(anchor, "message_id", ""),
                status=AIReplySuggestionStatus.IDLE,
                reason=reason,
            )

        built = self._prompt_builder.build_reply_suggestion_request(
            session,
            messages,
            task_id=self._task_id(AIAssistAction.REPLY_SUGGESTION.value),
            current_user_id=current_user_id,
        )
        running = AIReplySuggestionState(
            session_id=session.session_id,
            anchor_message_id=built.anchor_message.message_id,
            status=AIReplySuggestionStatus.RUNNING,
            task_id=built.request.task_id,
        )
        self._reply_suggestions[session.session_id] = running

        snapshot = await self._task_manager.run_once(built.request)
        state = self._state_from_snapshot(session.session_id, built.anchor_message.message_id, snapshot)
        self._reply_suggestions[session.session_id] = state
        return state.copy()

    def get_suggestions(self, session_id: str) -> AIReplySuggestionState | None:
        """Return current in-memory reply suggestions for a session."""
        state = self._reply_suggestions.get(str(session_id or "").strip())
        return state.copy() if state is not None else None

    def clear_suggestions(self, session_id: str) -> None:
        """Clear reply candidates for a session."""
        self._reply_suggestions.pop(str(session_id or "").strip(), None)

    def invalidate_for_sent_message(self, session_id: str) -> None:
        """Discard reply candidates once the user sends a message."""
        self.clear_suggestions(session_id)

    def invalidate_for_new_message(self, session_id: str, message: ChatMessage) -> None:
        """Discard candidates when the conversation receives a newer message."""
        normalized_session_id = str(session_id or "").strip()
        state = self._reply_suggestions.get(normalized_session_id)
        if state is None:
            return
        if message.session_id != normalized_session_id:
            return
        if message.message_id != state.anchor_message_id:
            self.clear_suggestions(normalized_session_id)

    async def close(self) -> None:
        """Clear in-memory state and release the singleton reference."""
        self._reply_suggestions.clear()
        global _ai_assist_manager
        if _ai_assist_manager is self:
            _ai_assist_manager = None

    def _reply_suggestion_eligibility(
        self,
        session: Session,
        messages: Sequence[ChatMessage],
        *,
        current_user_id: str,
        include_duplicate: bool,
    ) -> tuple[bool, str, ChatMessage | None]:
        if session.is_ai_session or session.session_type == "ai":
            return False, "ai_session", None
        if session.session_type not in {"direct", "private"}:
            return False, "unsupported_session_type", None

        anchor = latest_peer_text_message(messages, current_user_id=current_user_id)
        if anchor is None:
            return False, "no_peer_text_message", None

        state = self._reply_suggestions.get(session.session_id)
        if state is not None and state.anchor_message_id == anchor.message_id:
            if state.status in {AIReplySuggestionStatus.RUNNING, AIReplySuggestionStatus.READY}:
                if not include_duplicate:
                    return False, "duplicate_anchor", anchor
        return True, "", anchor

    def _state_from_snapshot(
        self,
        session_id: str,
        anchor_message_id: str,
        snapshot: AITaskSnapshot,
    ) -> AIReplySuggestionState:
        if snapshot.state == AITaskState.CANCELLED:
            return AIReplySuggestionState(
                session_id=session_id,
                anchor_message_id=anchor_message_id,
                status=AIReplySuggestionStatus.CANCELLED,
                task_id=snapshot.task_id,
                error_code=AIErrorCode.AI_USER_CANCELLED,
                reason=snapshot.finish_reason,
            )
        if snapshot.state != AITaskState.DONE:
            return AIReplySuggestionState(
                session_id=session_id,
                anchor_message_id=anchor_message_id,
                status=AIReplySuggestionStatus.FAILED,
                task_id=snapshot.task_id,
                error_code=snapshot.error_code or AIErrorCode.AI_MODEL_UNAVAILABLE,
                reason=snapshot.error_message or snapshot.finish_reason,
            )

        parsed = self._prompt_builder.parse_reply_suggestions(
            snapshot.content,
            limit=self._prompt_builder.REPLY_SUGGESTION_COUNT,
        )
        if not parsed:
            return AIReplySuggestionState(
                session_id=session_id,
                anchor_message_id=anchor_message_id,
                status=AIReplySuggestionStatus.FAILED,
                task_id=snapshot.task_id,
                error_code=AIErrorCode.AI_OUTPUT_INVALID,
                reason=AIErrorCode.AI_OUTPUT_INVALID.value,
            )

        return AIReplySuggestionState(
            session_id=session_id,
            anchor_message_id=anchor_message_id,
            status=AIReplySuggestionStatus.READY,
            items=[
                AIReplySuggestionItem(
                    text=text,
                    rank=index + 1,
                    anchor_message_id=anchor_message_id,
                    task_id=snapshot.task_id,
                )
                for index, text in enumerate(parsed)
            ],
            task_id=snapshot.task_id,
            reason=snapshot.finish_reason,
        )

    @staticmethod
    def _assist_result(action: AIAssistAction, snapshot: AITaskSnapshot) -> AIAssistResult:
        text = snapshot.content if snapshot.state == AITaskState.DONE else ""
        return AIAssistResult(
            task_id=snapshot.task_id,
            action=action,
            text=text,
            state=snapshot.state,
            error_code=snapshot.error_code,
            error_message=snapshot.error_message,
            truncated=snapshot.truncated,
            finish_reason=snapshot.finish_reason,
        )

    @staticmethod
    def _task_id(prefix: str) -> str:
        return f"{prefix}-{uuid.uuid4()}"


_ai_assist_manager: Optional[AIAssistManager] = None


def peek_ai_assist_manager() -> Optional[AIAssistManager]:
    """Return the existing AI assist manager singleton when present."""
    return _ai_assist_manager


def get_ai_assist_manager() -> AIAssistManager:
    """Return the global AI assist manager singleton."""
    global _ai_assist_manager
    if _ai_assist_manager is None:
        _ai_assist_manager = AIAssistManager()
    return _ai_assist_manager
